### PR TITLE
Modularized device class

### PR DESCRIPTION
**Pull request by joachimeichborn**
Changed modeling of devices from one hugh device class that models every
kind of devices to specific classes for each device type. Restructured
device initialization/updating to have the logic in the individual
device classes instead of bundling all in the configuration class. Split
view holders in separate files. Updated gradle build script to work with
up-to-date Android Studio. Added unit tests

### CODE REVIEW

**Comment by CurlyMoo** [comment]
What an awesome commit i must say. One issue though. I'm not a app developer and i got to the point i understood the old code base so i could maintain it. Not sure if i fully grasp the techniques you used here... :+1:

**Comment by joachimeichborn** [comment]
Thank you! Is there any specific question you have? If so, I am happy to answer it. Based on pilight I guess you are more familiar with C than Java and maybe the powerfull Java enums look strange to you? However, I am sure that maintaining the changed version will be a lot easier as I have untangled the monolithic device representation that existed before. So please let me know if you need any help understanding it!

**Comment by CurlyMoo** [comment]
Maybe we could just ask you to add new functionality when desired? Would you have interest and time for it?

**Comment by joachimeichborn** [comment]
You can of course ask me and I will see what I can do. However, in the next couple of months I will be quite busy with other stuff, so I guess it's rather unlikely that I will be able to actually do something in the near future.

**Comment by CurlyMoo** [comment]
For a start. The current pilight version allows only one master daemon with SSDP enabled. The rewrite code will allow multiple. That means we need a new screen that shows all found pilight instances and let users choose one of them, ofc besides the ip:port configuration that currently also exists.

**Pull request merged**
